### ISSUE TITLE
 Failed to load class files of expansion.

### ISSUE THREAD

**Issue by MASTERTACALE** [PlaceholderAPI/PlaceholderAPI#1012]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

javascript expansion not loading

### Expected Behaviour

should just load the javascript extension

### How to Reproduce

for me:

drop the javascript extension
start the server
error

get out the javascript extension
solved

but i need the javascript extension ;c
[latest.log](https://github.com/PlaceholderAPI/PlaceholderAPI/files/13037682/latest.log)

### `/papi dump` Output

https://paste.helpch.at/eyuziduvah

### Console Log

https://paste.helpch.at/simizudabe.makefile

### Errors

https://paste.helpch.at/odonovijiy.rb

### Additional Info

this only occurs when i start/restart the server but when i enter and put /papi reload all placeholders reload but the no external placeholders just disappear and idk ;c

**Comment by Andre601** [comment]
`Zip file closed`
This means that something closed the class loader PlaceholderAPI uses, resulting in this issue.

This also means that this is not an issue caused by PlaceholderAPI nor one we are likely able to fix.

**Comment by nakanotti** [comment]
The same problem occurs occasionally in my environment.
```
[11:04:56] [Server thread/ERROR]: Failed to load class files of expansion.
java.util.concurrent.CompletionException: zip file closed (expansion file: /data/plugins/PlaceholderAPI/expansions/Expansion-math.jar)
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:443) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:?]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[paper-1.20.4.jar:git-Paper-370]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.20.4.jar:git-Paper-370]
	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:421) ~[?:?]
	... 7 more
```
Since it doesn't happen all the time, it's possible that the Jar file is being closed due to other factors.

**Comment by nakanotti** [comment]
Perhaps it depends on when the "stream" object [here](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/c4a046ff24fc7490a0872ad0ccc28a684a83a659/src/main/java/me/clip/placeholderapi/util/FileUtil.java#L49C17-L49C17)  is destroyed?

**Comment by PiggyPiglet** [comment]
This is something that's come up again and again over time, not just with PAPI, but a lot of plugins I've used and worked on. Especially noticed it on projects I've used guice on, although PAPI doesn't use guice so definitely not that. The problem with finding the actual issue is that it seems to arise when there's lots of other plugins and expansions in use, presumably which also do something with class loading and jars that somehow interferes with the way papi does it. It's really hard to recreate these environments and narrow down the issue.

Do any of your plugins mess with classloading? Do you use /reload?

**Comment by nakanotti** [comment]
I haven't been able to confirm this problem recently, and it may have been an issue with another plugin. This problem is difficult to reproduce because it strangely appears and disappears on every reboot.

**Comment by PiggyPiglet** [comment]
I'm gonna leave this open but I'll be honest, I doubt we'll ever be able to fix this.

**Comment by EmanYm** [comment]
I am getting this error in Purpur 1.20.6-2206 (c637b74) and PlaceholderAPI 2.11.6 [downloaded from Hangar]

https://hastebin.com/share/ihogajajen.ruby
It throws the error during every server start and every time I type "/papi reload"

**Comment by Andre601** [comment]
> I am getting this error in Purpur 1.20.6-2206 (c637b74) and PlaceholderAPI 2.11.6 [downloaded from Hangar]
> 
> https://hastebin.com/share/ihogajajen.ruby It throws the error during every server start and every time I type "/papi reload"

By the looks of it does this not seem like a PAPI issue. Instead a plugin seems to modify/change some server code?
Either way, this isn't really PlaceholderAPI's fault here.

**Comment by BlitzOffline** [comment]
> I am getting this error in Purpur 1.20.6-2206 (c637b74) and PlaceholderAPI 2.11.6 [downloaded from Hangar]
> 
> https://hastebin.com/share/ihogajajen.ruby It throws the error during every server start and every time I type "/papi reload"

To add to @Andre601's reply, A PlaceholderAPI expansion from vk2gpz (one related to enchantments) is making this breaking modification. PlaceholderAPI is mentioned in the error because it is the one loading the expansion, and most likely, the expansion makes the modification during loading. (expansions are loaded on server start and on `/papi reload`).

**Comment by EmanYm** [comment]
Out of the expansions that I use, I narrowed it down to this [Enchantment expansion](https://wiki.placeholderapi.com/users/placeholder-list/#enchantment)

**Comment by perlsol** [comment]
I spent a week on this and never got to actually find out why this happened in my case until I took the plunge and swapped the test server to production and switched the old production off, then all the problems went away!
For some people this is indeed a bad/corrupted expansion or plugin, once you have replaced them all to make sure of this with luck your problem will have gone, sadly that wasn't the case for me. almost every restart caused a random expansion to fail with this error, I have over 100 plugins and 15 expansions so as you can understand, working through all of these 1 at a time was a nightmare to say the least!
I tracked it down to one simple thing... I was running the production AND our test server on the same physical machine, both running the exact same plugins and expansions. Once I shutdown the test server I never had any more problems, I can therfore only put it down to a namespace of a process being shared and it not liking it maybe \o/
This would also explain why some people couldn't replicate this issue as even if I gave you a fully copy of my server and you fired it up, you wouldn't have an issue at all, not unless you too fired up 2 instances ;)
Glad that is all over, and I hope my findings helps someone in the future!

**Comment by Kqliber** [comment]
Still having difficulties having to replicate even with 2 server instances open and a few expansions on each server
Could you provide some steps to replicate, or is it literally as simple as just 2 server instances?

I don't really see this as a plausible explanation anyway, I'm no expert, but even if the servers are running on the same java path/binary/executable, the servers will be running on 2 different JVM instances with their own allocated memory, alongside 2 different plugin JARs, different expansion JARs (even if technically the same version). If this was the case, I'd imagine every plugin would also fail to load. 
If it works for you though, great

As a side note, there is currently an open [PR](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/859) that has a potential to fix this, would you be able to compile this and see if it fixes your issue even with 2 server instances open?

**Comment by perlsol** [comment]
I have no idea how outside of the JVM how they could effect each other but not having two running certainly stopped my errors.
Maybe it is a windows only thing \o/ my setup is windows server 2019 with 12Gb (prod) and 8Gb (test) allocated.
I do need to fire up the test server again soon so will get chance to keep an eye on this and will report back.
