### ISSUE TITLE
CommandException on ecloud list installed

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#102]
Spigot 1.14 (2220) or Spigot 1.13.2 final
PlaceholderAPI 2.9.2-DEV-61

```
>papi enablecloud
[20:50:31 INFO]: [PlaceholderAPI] Fetching available expansion information...
[20:50:31 INFO]: The cloud has been enabled!
[20:50:32 INFO]: [PlaceholderAPI] 125 placeholder expansions are available on the cloud.
>papi ecloud list installed
[20:50:33 INFO]: Showing expansions for: all installed -- amount: 10 page: 1/1
[20:50:33 INFO]: Green = Expansions you have
[20:50:33 INFO]: Gold = Expansions which need updated
[20:50:33 WARN]: Unexpected exception while parsing console command "papi ecloud list installed"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.9.2-DEV-61
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class java.util.TreeMap$Entry cannot be cast to class java.lang.Comparable (java.util.TreeMap$Entry and java.lang.Comparable are in module java.base of loader 'bootstrap')
        at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?]
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at me.clip.placeholderapi.commands.ExpansionCloudCommands.onCommand(ExpansionCloudCommands.java:323) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:101) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        ... 8 more
>papi disablecloud
```

Same test servers
PlaceholderAPI 2.9.2-DEV-59
```
[15:18:17] [Server thread/INFO]: The cloud has been enabled!
[15:18:18] [Craft Scheduler Thread - 21/INFO]: [PlaceholderAPI] 124 placeholder expansions are available on the cloud.
[15:18:19] [Server thread/INFO]: Showing expansions for: all installed -- amount: 10 page: 1
/1
[15:18:19] [Server thread/INFO]: Green = Expansions you have
[15:18:19] [Server thread/INFO]: Gold = Expansions which need updated
[15:18:19] [Server thread/INFO]: 1: Player -- http://api.extendedclip.com/media/PAPI-Expansion-Player_xY7OUz3.jar
[15:18:19] [Server thread/INFO]: 2: Parkour -- http://api.extendedclip.com/media/Expansion-Parkour_hgFfoD8.jar
[15:18:19] [Server thread/INFO]: 3: Essentials -- http://api.extendedclip.com/media/PAPI-Expansion-Essentials_zn0FSu4.jar
[15:18:19] [Server thread/INFO]: 4: WorldGuard -- http://api.extendedclip.com/media/Expansion-WorldGuard-1.2.0.jar
[15:18:19] [Server thread/INFO]: 5: Skript -- http://api.extendedclip.com/media/Expansion-Skript_bGsPupR.jar
[15:18:19] [Server thread/INFO]: 6: LuckPerms -- http://api.extendedclip.com/media/Expansion-LuckPerms_2ZvigdN.jar
[15:18:19] [Server thread/INFO]: 7: Thirst -- http://api.extendedclip.com/media/Expansion-Thirst_BWspLom.jar
[15:18:19] [Server thread/INFO]: 8: ViaVersion -- http://api.extendedclip.com/media/Expansion-ViaVersion_yeaWuoM.jar
[15:18:19] [Server thread/INFO]: 9: Multiverse -- http://api.extendedclip.com/media/Expansion-Multiverse.jar
[15:18:19] [Server thread/INFO]: 10: Disease -- http://api.extendedclip.com/media/DiseasePlaceholders-0.0.1_MBTTwH2.jar
[15:18:20] [Server thread/INFO]: The cloud has been disabled!
```

**Comment by SlimeDog** [comment]
Confirmed PAPI 2.10.0 working nicely on both Spigot 1.13.2 final and Spigot 1.14 (2254). Thank you.

**Comment by extendedclip** [comment]
Thanks for the feedback. Sorry for the wait. Glad we got this sorted out.
