### ISSUE TITLE
Expansion-Player fails for consumer

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#105]
Server Java 11.0.3
Spigot 1.14 (2248)
PlaceholderAPI 2.9.2-DEV-61
Expansion-Player 1.6.5
TabList 4.3

### Issue
Player placeholders parse correctly with PAPI, but do not parse with TabList and generate errors (every trigger). Header is not displayed (I don't display footer), only player list. No issues with Spigot 1.13.2 final, otherwise same configuration.

Filed this issue with TabList [first](https://github.com/montlikadani/TabList/issues/83). TabList developer says:
```
It seems this is not the TabList problem, because this error comes to my code which only replaces the PlaceholderAPI placeholders.
The Player expansion on PAPI is using the deprecated version, that the 1.14 does not support anymore. PlaceholderAPI/Player-Expansion@c73bf08#diff-2a880cd46327aa24610ed2958af2a5c7R176
```

### Console errors
```
[10:28:00] [Craft Scheduler Thread - 6/WARN]: [TabList] Plugin TabList v4.3 generated an exception while executing task 96
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getServerName()Ljava/lang/String;
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:176) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
        at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1433) ~[?:?]
        at hu.montlikadani.tablist.Variables.replaceVariables(Variables.java:67) ~[?:?]
        at hu.montlikadani.tablist.TabList.sendTab(TabList.java:714) ~[?:?]
        at hu.montlikadani.tablist.TabList.access$1(TabList.java:658) ~[?:?]
        at hu.montlikadani.tablist.TabList$1.run(TabList.java:623) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar-2019-05-01-0918:git-Spigot-1eece4f-1fa9a81]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar-2019-05-01-0918:git-Spigot-1eece4f-1fa9a81]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### How to reproduce
1. Load Expansion-Player
1. PAPI reload
1. Connect player
1. Verify that PAPI parse works as expected
1. Observe spam of errors
1. Observe that TabList does not

**Comment by Andre601** [comment]
There is a PR on the player repo that deals with the issue that `%player_server%` doesn't work.
https://github.com/PlaceholderAPI/Player-Expansion/pull/18

We have to wait for the fix to be applied :/

**Comment by SlimeDog** [comment]
Well, c'mon clip. :)

**Comment by aBo0oDyy** [comment]
Looks like the PR needs some changes before it get merged.

**Comment by SlimeDog** [comment]
Verified that other consumed Player placeholders succeed
- %player_x%
- %player_y%
- %player_z%
- probably all the others (not tested)

when %player_server% is not referenced.

**Comment by SlimeDog** [comment]
Confirm that %server_name% is recognized by Spigot 1.13.2 and 1.14, with appropriate configurations.
