### ISSUE TITLE
1.21.1 support?

### ISSUE THREAD

**Issue by DamAlyuk** [PlaceholderAPI/PlaceholderAPI#1083]
### Confirmation

- [X] I checked the Issues and Pull request tab for any existing issues or PRs.
- [X] My Feature Request is for **PlaceholderAPI** and not any expansion or other plugin.

### Type

New API feature

### Description

May you add 1.21.1 support for Purpur

**Comment by Andre601** [comment]
Did you actually test that PlaceholderAPI doesn't work on 1.21.1?

**Comment by DamAlyuk** [comment]
I don't see any version build for 1.21.1. nowhere? Or you wanna say that 1.20.6 works on 1.21.1?

**Comment by DamAlyuk** [comment]
Okay, it works, but is there any issues cause of difference between versions?

**Comment by Andre601** [comment]
Have you just tried?
Not every plugin needs a new build for every version.

**Comment by Andre601** [comment]
> Okay, it works, but is there any issues cause of difference between versions?

Unless some have been reported here already, no.

**Comment by GruenerNinja** [comment]
Sadly for me it doesn't work i get in the console this i hope it is helpful 

Suppressed: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/PlaceholderAPI-2.11.6.jar'
		at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
	Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/PlaceholderAPI-2.11.6.jar'
		at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
		... 4 more
	Caused by: java.lang.RuntimeException: Failed to execute task me/clip/placeholderapi/PlaceholderAPIPluginL10
		at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
		at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
		at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
		... 4 more
	Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key a (attempted merging values private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljavassist/ws/a; and private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljava/io/File;)
		at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
		at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
		at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
		at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
		at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
		at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
		... 4 more
	Caused by: java.lang.IllegalStateException: Duplicate key a (attempted merging values private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljavassist/ws/a; and private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljava/io/File;)
		at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
		at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
		at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709) ~[?:?]
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702) ~[?:?]
		at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:122) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
		at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1742) ~[?:?]
		at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
		at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:178) ~[purpur-1.21.1.jar:?]
		at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
		... 3 more

**Comment by EterNityCH** [comment]
@GruenerNinja I am afraid to inform you that you have malware my friend.

**Comment by mja00** [comment]
@GruenerNinja you've got malware in your jar files

**Comment by GruenerNinja** [comment]
why you think so ? Im running the plugin from the official source @EterNityCH

**Comment by EterNityCH** [comment]
Evidence is present in your error above. You should remove all jar files from your server and redownload them from trusted source. 

If the server is not isolated, a full system wipe is recommended.

**Comment by GruenerNinja** [comment]
Im running Purpur latest Build an Luckperms Vault Placeholder-Api and Tab Plugin all form ether spigot or hanger mc or from LP direct so i don't think that i have malware. But may you can tell me what makes you so sure that i have malware ( line in the error code )

**Comment by Timongcraft** [comment]
javassist, you can also try to check the hash from your jar and the original, it won't match.

**Comment by Andre601** [comment]
The error reports Neoforge, which makes me believe you either use a hybrid server, or the jar was tempered with somehow, as was mentioned @GruenerNinja 

Double check that this error perists on a **fresh server setup with just PlaceholderAPI present**.
And always provide your full server logs through https://mclo.gs or a paste site.

**Comment by EterNityCH** [comment]
Neoforge is present becusse Paper remapper uses them. The issue has already be identified as the malware infested jars. His top priority right now is to clean and secure his server.

**Comment by Andre601** [comment]
> Neoforge is present becusse Paper remapper uses them. The issue has already be identified as the malware infested jars. His top priority right now is to clean and secure his server.

Could you provide more clear info on what proofs there being malware? It's not really clear to me (And most likely GreunerNinja too) on what makes you say that actually.
I'm sure it would help everyone here in knowing the reasons for why this may be a malware-infected jar.

**Comment by EterNityCH** [comment]
> Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key a (attempted merging values private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljavassist/ws/a; and private static me/clip/placeholderapi/PlaceholderAPIPluginL10/a Ljava/io/File;)

This is the proof as @Timongcraft mentioned above.

**Comment by EterNityCH** [comment]
I am glad it does not cause any damage to your server. 

If you work alongside with multiple developers in your organization, I recommend conducting a security audit to determine the origin source of the infested jar so incident like this does not reappear again in the future. 👍

**Comment by GruenerNinja** [comment]
thank you for your help. Im still working solo and also the infested version just ran like 3 min total on the system but im still curious how i got this version i guess something that i will never find out.

**Comment by ImJustNozell** [comment]
yes, work in 1.21 tested by me

**Comment by ImJustNozell** [comment]
is a more beatifull complement , very completed

**Comment by s-j-y-m** [comment]
一个关于版本支持的问题下,居然还有一个后门问题,bro,意料之外
A backdoor issue under a question about version support, bro, unexpected!
