### ISSUE TITLE
Lastest Spigot 1.14 as of this posting NULL pointer on server shutdown

### ISSUE THREAD

**Issue by DalBrar** [PlaceholderAPI/PlaceholderAPI#109]
Booted up newest papi 2.10 update with the most recent build of spigot 1.14 and right after server booted I forgot I needed to change something so I shut it down 3 seconds after it had finished loading and noticed this error:

`[10:06:45] [Craft Scheduler Thread - 1/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.0 generated an exception while executing task 3
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$null$6(ExpansionCloudManager.java:183) ~[?:?]
        at java.util.Map.forEach(Unknown Source) ~[?:1.8.0_211]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$7(ExpansionCloudManager.java:178) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[custom.jar:git-Spigot-1eece4f-84400e6]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [custom.jar:git-Spigot-1eece4f-84400e6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by darbyjack** [comment]
Can you try this on the latest development build? Not able to reproduce.

**Comment by aBo0oDyy** [comment]
Hey @DalBrar,
Is it still not working with the latest version?

Will close the issue in the next few days if we didn't get a reply from you.
