### ISSUE TITLE
[Suggestion]: Only print error and not stacktrace when expansion can't be loaded.

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/PlaceholderAPI#114]
## The issue
When PlaceholderAPI tries to load an expansion that can't be loaded because of a missing dependency, then it throws a stacktrace which could get spammy if there are multiple expansions with that issue.

For example: This stacktrace is thrown when the expansion for LuckPerms is installed, but LuckPerms is missing/not enabled:
```
[13:12:13] [Server thread/ERROR]: Could not pass event ServerLoadEvent to PlaceholderAPI v2.10.1
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
	at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:49) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:99) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:151) ~[?:?]
	at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoadEventListener.java:22) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-20]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-20]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:466) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-20]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-20]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	... 13 more
```

## The idea
My idea is to change this to just show an error message instead of the stacktrace for a cleaner console and perhaps only show stacktrace if a config option of PlaceholderAPI is active.

The message could be like:
```
[13:12:13] [Server thread/WARN]: Could not load the expansion "LuckPerms". Is a dependency missing?
```

**Comment by aBo0oDyy** [comment]
Adding it as an option in config would be good i guess, since i think it will say the same thing for API changes. So the dependency exists but has newer/older version of the AP and this error helps updating/fixing that.

**Comment by Andre601** [comment]
I think a debug option in the config (with default being false) would be good.
And when a expansion can't be loaded, send this message:
```
Expansion {expansion} couldn't be loaded.
Set "debug" to true for more details.
```

**Comment by darbyjack** [comment]
Implemented in the latest update.
