### ISSUE TITLE
error place MarriageMAster...

### ISSUE THREAD

**Issue by LordRamma** [PlaceholderAPI/PlaceholderAPI#148]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issue]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

### Expected behaviour
> What should PlaceholderAPI do?

### Actual behaviour
> What does PlaceholderAPI actually do?

### How to reproduce
> What steps did you made, to get this bug?

1. 
[15:16:53 WARN]: Unexpected exception while parsing console command "papi reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.3.jar:git-Paper-132]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) ~[patched_1.14.3.jar:git-Paper-132]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:421) ~[patched_1.14.3.jar:git-Paper-132]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-132]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-132]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassCastException: at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be cast to at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster
        at com.extendedclip.papi.expansion.marriagemaster.MarriageMasterExpansion.register(MarriageMasterExpansion.java:46) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:105) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:176) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:226) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-132]
        ... 8 more

**Comment by Andre601** [comment]
> **Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

**Comment by darbyjack** [comment]
Exactly what Andre said. Also, if you choose to ignore the template, you will not receive support.

**Comment by LordRamma** [comment]
tks
