### ISSUE TITLE
 'task 107' occurs NullPointerException when starting server every time (But will not crash the plugin)

### ISSUE THREAD

**Issue by i493052739** [PlaceholderAPI/PlaceholderAPI#265]
### Issue
> 'task 107' occurs NullPointerException when I starting server every time (But it will not crash the plugin)

21.03 13:18:42 [Server] Craft Scheduler Thread - 30/WARN Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 107
21.03 13:18:42 [Server] INFO java.lang.NullPointerException: null
21.03 13:18:42 [Server] INFO at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$null$3(ExpansionCloudManager.java:181) ~[?:?]
21.03 13:18:42 [Server] INFO at java.util.Map.forEach(Unknown Source) ~[?:1.8.0_201]
21.03 13:18:42 [Server] INFO at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:172) ~[?:?]
21.03 13:18:42 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServerAsync-1.12.2-51d82d9]
21.03 13:18:42 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServerAsync-1.12.2-51d82d9]
21.03 13:18:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
21.03 13:18:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
21.03 13:18:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

### Expected behaviour
> no NullPointerException 

### Actual behaviour
> NullPointerException will occur once time after the server started

### How to reproduce
> 
1.  Using the CatServer-Core  https://github.com/Luohuayu/CatServer/releases
2. Put PlaceholderAPI (latest version 2.10.4 - to 2.8.2) into the 'plugins' folder
3. startup the server.

Many thanks, and looking for your reply~

**Comment by A248** [comment]
I experience the same error. Although the beginning of the stacktrace is slightly different, because I'm using Paper 1.8.8, the problematic line is still the same:
https://pastebin.com/1KTVm1We

Line causing the NPE: 
`me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:172)`

**Comment by x1p** [comment]
Saw something similar on 1.15.2 paper fork
```
[05:00:55] [Craft Scheduler Thread - 5/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.5-DEV-85 generated an exception while executing task 18
java.lang.NullPointerException: null
	at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:174) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Purpur-507]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Purpur-507]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
PlaceholderAPI v2.10.5-DEV-85

**Comment by darbyjack** [comment]
Should be fixed. Rolled out 2.10.5 last night.
