### ISSUE TITLE
Error at the end of the start-up

### ISSUE THREAD

**Issue by AndiSlash0723** [PlaceholderAPI/PlaceholderAPI#267]
I got this error at the end of the start-up this morning but everything was fine last night (no error)

I'm currently running 1.15.2 Paper Spigot and using the latest version of PlaceholderAPI from spigotmc.org

`[10:03:49 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 11
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 110289 path $..placeholders[24]
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-143]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-143]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-143]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 110289 path $..placeholders[24]
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1017) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418) ~[patched_1.15.2.jar:git-Paper-143]        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406) ~[patched_1.15.2.jar:git-Paper-143]        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[patched_1.15.2.jar:git-Paper-143]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.15.2.jar:git-Paper-143]
        ... 9 more`

Sorry im new to coding and I dont really know about Java, is this error caused  by other plugin? or is there any way i can fix that? Please help >.<

Thanks!

**Comment by 90poitu** [comment]
@AndiSlash0723. They announce that PAPI is having a problem connect to ecloud. They said it will be up soon. They have a team working on it ASAP. For now, you can download the expansion manually https://placeholderapi.com/ecloud and once you download the expansion, just put it in your /plugins/PlaceholderAPI/expansions/ folder

**Comment by AndiSlash0723** [comment]
@90poitu 
AHHHH got it, so theres no way that i can "fix" this...
Seems i can ignore this error? 
I think i can close this, thanks!
