### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Stixil** [PlaceholderAPI/PlaceholderAPI#278]
Error causing this to get logged every few seconds or so and eventually crash the server. 

Installed expansions:  Bungee, Essentials, Pinger, Player, Server, StaffFacilities, Statistic, Vault

[01:06:38] [Craft Scheduler Thread - 5/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.5 generated an exception while executing task 485
java.lang.NullPointerException: null
	at me.xanium.gemseconomy.vault.GEVaultHook.getBalance(GEVaultHook.java:101) ~[?:?]
	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
	at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-121]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-121]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by darbyjack** [comment]
Contact the author of GemsEconomy, issue is on their end.
