### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by mcfenmap** [PlaceholderAPI/PlaceholderAPI#303]
`[05:13:26 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 41
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$null$3(ExpansionCloudManager.java:190) ~[?:?]
        at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_241]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:182) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-1.15.2-b240.jar:git-Paper-239]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[Paper-1.15.2-b240.jar:git-Paper-239]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper-1.15.2-b240.jar:git-Paper-239]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by Andre601** [comment]
Use one of the templates please. They exist for a reason.

**Comment by aBooDyy** [comment]
Hello there,

It seems like your machine/host/server couldn't connect to the [eCloud](https://api.extendedclip.com/home/) for automatic expansion download, which is why you're getting that error.
You can manually download expansions from [here](https://api.extendedclip.com/all/). You can also disable the plugin from trying to connect to the eCould from the config (by disabling `cloud_enabled` option) to avoid getting the error.

As Andre mentioned, use the appropriate template for your issue next time, please.

Have a nice day,
aBooDyy
