### ISSUE TITLE
AnimatedScoreboard Placeholderapi issue for some players

### ISSUE THREAD

**Issue by vlOd2** [PlaceholderAPI/PlaceholderAPI#326]
#13 # Issue
> What is the issue? Describe it like you would tell a friend.

When players with "_" in their names the placeholders on AnimatedScoreboard dont show for them and cause an issue! And yes i checked the console and its an PlaceHolderApi issue

### Expected behaviour
> What should PlaceholderAPI do?

Dont cause an issue while displaying the placeholders or the scoreboard

### Actual behaviour
> What does PlaceholderAPI actually do?

Doesnt display the placeholders,cause spam in console and doesnt display the scoreboard at all

### How to reproduce
> What steps did you made, to get this bug?

Join with a long name like Cool_Bloo1221 and make sure it contains an "_" and boom

### Potentialy helpful info
Only happens with the players who meet the condition i described in the "### How to reproduce" section!
I tested with other accounts and it doesnt do the same
It works normally

Idk if its a plugin issue for AnimatedScoreboard or its a placeholderapi issue i can asume its a placeholderapi issue because of the console logs!

Console Logs:

> [ERROR] [AnimatedScoreboard] Something went wrong during a scoreboard tick of Cool_Bloo1221:
> 
> [WARNING] java.lang.NullPointerException
> 
> [WARNING] at ro.Marius.TheBridge.Scoreboard.PlaceholderAPI.DataExpansion.onPlaceholderRequest(DataExpansion.java:62)
> 
> [WARNING] at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
> 
> [WARNING] at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
> 
> [WARNING] at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:375)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholders(PlaceholderHandler.java:19)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.setLine(PlayerScoreboard.java:187)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.forceUpdate(PlayerScoreboard.java:121)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.registerTeams(PlayerScoreboard.java:160)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.setState(PlayerScoreboard.java:142)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.impl.PacketImplementation.initialize(PacketImplementation.java:50)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.initialize(PlayerScoreboard.java:136)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.objects.ScoreboardPlayer.tickScoreboards(ScoreboardPlayer.java:284)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.core.PlayerScoreboardHandler.lambda$init$1(PlayerScoreboardHandler.java:154)
> 
> [WARNING] at me.jasperjh.animatedscoreboard.core.PlayerScoreboardHandler$$Lambda$191.00000000087151E0.run(Unknown Source)
> 
> [WARNING] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
> 
> [WARNING] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> 
> [WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 
> [WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 
> [WARNING] at java.lang.Thread.run(Thread.java:813)

And it spams that over and over
I think its an hook issue but i could be wrong!

Thank you and i hope you will help me! :D

**Comment by vlOd2** [comment]
Found that only for the player i mentioned happens like i teste myself and nothing happens it works as intended

**Comment by vlOd2** [comment]
Closed:

Its an plugin issue "The Bridge"
