### ISSUE TITLE
Enabling Error

### ISSUE THREAD

**Issue by RRR9996** [PlaceholderAPI/PlaceholderAPI#37]
So, I was adding Placeholder so I could add more things like uptime. But when I restarted my server on server.pro it says enabling, and then almost instantly an error. This is it:
`[ERROR] Error occurred while enabling PlaceholderAPI v2.9.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/Gson
at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.<init>(ExpansionCloudManager.java:54) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPIPlugin.enableCloud(PlaceholderAPIPlugin.java:182) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPIPlugin.onEnable(PlaceholderAPIPlugin.java:90) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8.jar:git-Bukkit-7019900]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
... 14 more`

I hope someone can help.

**Comment by darbyjack** [comment]
Alright,

I've actually seen this error. So basically what's going on is that in Spigot 1.8.3, something was added called Gson into the server jars that basically helps store data and whatnot, Gson is Google's version of JSON, which I'm sure you probably know what that is since you've seen it before in different plugins (files that end in .json).

Your current issue is that you are trying to use a Spigot 1.8 jar, and since PlaceholderAPI uses the Gson inside of the server jar, it's not possible to get it since you are trying a version lower than 1.8.3.

My solution would be to run BuildTools and specify that you'd like the version 1.8.8, it's still on MC 1.8.x line so it should fit your needs, plus it'll have the Gson support and the PlaceholderAPI ecloud will work!

**Comment by RRR9996** [comment]
Well, this is not a problem, but thanks for telling me how to fix it. 

Good thing my other plugin supports 1.8 - 1.13.
