### ISSUE TITLE
Expansions need updating

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#381]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

Spigot 1.16.1
PlaceholderAPI 2.10.7-DEV-39

Somewhere after dev build 35, (nearly) all the clip-authored expansions were broken either on start-up or when used by QuickBoard or TabList (both latest releases):
- Player
- Server
- Statistic
- Thirst
- Vault
- WorldGuard
- etc

Typical example start-up error
```
[03:51:00] [Server thread/ERROR]: [PlaceholderAPI] expansion class VaultExpansion is outdated:
Failed to load due to a [NoClassDefFoundError], attempted to use com/extendedclip/papi/expansion/vault/VaultPermsHook
```

### Installed expansions
> Please list all expansions that are displayed when running `/papi list`

```
>papi list
[04:14:05] [Server thread/INFO]: 25 placeholder hook(s) active: 
  DeluxeMenus, aac, bentobox, biomeremap, bskyblock, challenges, combatlogx, coordinatetool, denizen, disease
  essentials, frp, insights, level, mobhunting, multiverse, plan, player, quests, residence
  server, spark, stat, statistic, viaversion
```

Typical QB error
```
[04:37:21] [Server thread/WARN]: [QuickBoard] Task #54 for QuickBoard v4.4.1 generated an exception
java.lang.NoClassDefFoundError: com/extendedclip/papi/expansion/player/PlayerUtil
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:299) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:180) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:76) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:508) ~[?:?]
        at me.tade.quickboard.PlayerBoard.setHolders(PlayerBoard.java:200) ~[?:?]
        at me.tade.quickboard.PlayerBoard.setUpText(PlayerBoard.java:125) ~[?:?]
        at me.tade.quickboard.PlayerBoard.startSetup(PlayerBoard.java:99) ~[?:?]
        at me.tade.quickboard.PlayerBoard.<init>(PlayerBoard.java:67) ~[?:?]
        at me.tade.quickboard.QuickBoard.createDefaultScoreboard(QuickBoard.java:229) ~[?:?]
        at me.tade.quickboard.QuickBoard$2.run(QuickBoard.java:121) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar-2020-07-24-1727:git-Spigot-9639cf7-7c03d25]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.extendedclip.papi.expansion.player.PlayerUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 18 more
```

**Comment by SlimeDog** [comment]
Do QuickBoard and TabList need to update to conform with the new regime?

**Comment by Sxtanna** [comment]
> Do QuickBoard and TabList need to update to conform with the new regime?

No, this is completely my fault.
Expansions functioning properly before was a complete and total side-effect of the expansion discovery mechanism.

This side effect was eliminated due to a loading optimization I made in ee33de5.

I will look into a way to restore this behaviour.

**Comment by SlimeDog** [comment]
Confirmed fixed in dev build 40. Thank you.

**Comment by Sxtanna** [comment]
For the record, I am not happy with this.

**Comment by SlimeDog** [comment]
Why? What is the issue?

**Comment by Sxtanna** [comment]
No, don't worry about it. It's nothing to concern yourself with.
