### ISSUE TITLE
Console Spam with VentureChat & PAPI

### ISSUE THREAD

**Issue by mercurialmusic** [PlaceholderAPI/PlaceholderAPI#4]
Getting this every time someone says something in chat, running the latest version. Also posting this on the VentureChat page, but this is only happening since the latest PAPI update: https://pastebin.com/reR0bTY4

`[13:52:00] [Async Chat Thread - #27/ERROR]: Could not pass event AsyncPlayerChatEvent to VentureChat v2.12.2
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition
{player_name}
    at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.closure(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_162]
    at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_162]
    at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_162]
    at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:203) ~[?:?]
    at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:167) ~[?:?]
    at mineverse.Aust1n46.chat.utilities.Format.convertPlaceholders(Format.java:146) ~[?:?]
    at mineverse.Aust1n46.chat.utilities.Format.convertToJson(Format.java:110) ~[?:?]
    at mineverse.Aust1n46.chat.listeners.ChatListener.onAsyncPlayerChatEvent(ChatListener.java:688) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor909.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_latest.jar:git-Spigot-c3093ef-aa25568]
    ... 11 more`

**Comment by extendedclip** [comment]
Thank you. I have a solution for this and will submit a fix soon.
