### ISSUE TITLE
Random stacktrace upon start

### ISSUE THREAD

**Issue by clrxbl** [PlaceholderAPI/PlaceholderAPI#413]
### Issue
> What is the issue? Describe it like you would tell a friend.

Random stacktrace upon server start, plugin seems to function normally otherwise

```
[17:26:55 WARN]: [PlaceholderAPI] failed to download expansion information
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1651) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.findExpansionByName(LocalExpansionManager.java:127) ~[?:?]
at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$null$7(CloudExpansionManager.java:196) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_242]
at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$fetch$8(CloudExpansionManager.java:192) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]
... 6 more
```

### Expected behaviour
> What should PlaceholderAPI do?

Not output a stacktrace

### Actual behaviour
> What does PlaceholderAPI actually do?

Magic

### How to reproduce
> What steps did you made, to get this bug?

./start.sh

### Installed expansions
> Please list all expansions that are displayed when running `/papi list`

1. LuckPerms luck Y 5.0-R2
2. Player clip Y 1.7.2
3. PlotSquared intellectualsites Y 3
4. Vault clip Y 1.6.0

**Comment by Andre601** [comment]
Can we actually SEE the stacktrace?
We can't provide any help whatsoever, if we don't know the source of an issue.

**Comment by clrxbl** [comment]
Oh I'm stupid my bad, never included the stacktrace here, was sidetracked.

```
[17:26:55 WARN]: [PlaceholderAPI] failed to download expansion information
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1651) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.findExpansionByName(LocalExpansionManager.java:127) ~[?:?]
at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$null$7(CloudExpansionManager.java:196) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_242]
at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$fetch$8(CloudExpansionManager.java:192) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]
... 6 more
```

**Comment by Andre601** [comment]
What is your PlaceholderAPI version, Server version and plugins installed? Any other errors on startup?

We will look into this issue.

**Comment by clrxbl** [comment]
Was the only error on startup and oddly enough didn't happen after.

This server is running Paper version git-Paper-101 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

PlaceholderAPI (2.10.8)


Am quite behind in terms of Paper versions which I'm aware of.

**Comment by Andre601** [comment]
Could be an issue for PAPI loading the expansions for the first time. Like mentioned will we look into this and hopefully find a fix for it.

**Comment by extendedclip** [comment]
Can you guys test build 105 on jenkins? https://ci.extendedclip.com/job/PlaceholderAPI/105/

If it works thank @MrIvanPlays, if not, blame @MrIvanPlays

**Comment by MrIvanPlays** [comment]
> blame @MrIvanPlays

:eyes:

**Comment by clrxbl** [comment]
I haven't been able to reproduce the issue at all, so will be hard to report back.

**Comment by extendedclip** [comment]
at least leave a response when you startup with build 105 haha

**Comment by clrxbl** [comment]
Well, it boots without issues.

**Comment by extendedclip** [comment]
https://ci.extendedclip.com/job/PlaceholderAPI/107/

**Comment by MrIvanPlays** [comment]
Well after this responce:

> I haven't been able to reproduce the issue at all since it happened, so will be hard to report back.

I think this issue to get triggered had a 1 of a million chance. I think that I got it right with my changes tho.

**Comment by Andre601** [comment]
Is this still happening to any of you?

**Comment by clrxbl** [comment]
Cannot reproduce, seems resolved.
