### ISSUE TITLE
Statistic placeholder

### ISSUE THREAD

**Issue by GilsJunior** [PlaceholderAPI/PlaceholderAPI#421]
### Issue

I have a towny server and I wanted to heave some leaderboards to show people who the top players are. 
To get the leaderboards, I bought the Leaderheads plugin on spigot. It told me on their wiki I should use the placeholders and change the yml files after. Basicly when I wanted to download the placeholders. It told me it got installed succesfully. Reloading didn't work tho so I restarted the server to hopefully make it work. When I tried validating the leaderboard. It said the placeholder didn't get download properly. Thats when I started asking around. Clips told me to make this github after so he won't forget. The bug occured with the placeholder %Time_seconds_played%.

### Expected behaviour

I think placeholdersAPI should make it compatible or update it so I can use it for my leaderboards.

### Actual behaviour

Update the placeholder of Leaderheads to make it work.

### How to reproduce

1. /papi ecloud download Leaderheads
2. /papi reload. (Here it started bugging. Reload wasn't getting executed)
3. Error occured in console.
4. Trying %time_seconds_played% ingame. (Said the placeholder wasnt properly installed)

### `/papi dump` output

https://paste.helpch.at/zoyuvirido

Heres the error:
>.... [15:42:47 WARN]: [PlaceholderAPI] Task #223120 for PlaceholderAPI v2.10.9 generated an exception
java.lang.NullPointerException: null
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:343) ~[?:?]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:138) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_262]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_262]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_262]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_262]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_262]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_262]
at java.util.stream.LongPipeline.reduce(LongPipeline.java:461) ~[?:1.8.0_262]
at java.util.stream.LongPipeline.sum(LongPipeline.java:419) ~[?:1.8.0_262]
at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593) ~[?:1.8.0_262]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Purpur-688]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Purpur-688]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1363) ~[patched_1.16.1.jar:git-Purpur-688]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.1.jar:git-Purpur-688]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1282) ~[patched_1.16.1.jar:git-Purpur-688]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1008) ~[patched_1.16.1.jar:git-Purpur-688]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-688]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

Kind regards, 

GilsJunior

**Comment by Andre601** [comment]
Is this still a thing with latest Dev build or is it fixed?

**Comment by simoneedotexe** [comment]
Can confirm in Dev build 111 on 1.16.4 https://pastebin.com/k0stPjbD

**Comment by Andre601** [comment]
Hey @simoneedotexe and @GilsJunior 

Just wanted to let you know that we may have found the actual issue for the NPE. Apparently did this error happen if one of the expansions (So far an old version of SpeedPerSec) doesn't contain any classes to load, making the entire loading process broken.

Could you try out the latest dev builds on Jenkins and let us know if the issue persists or if it is fixed? Thanks in advance for a response.

**Comment by emiisss** [comment]
still no fix ?
