### ISSUE TITLE
 Placeholder api now breaks morefish

### ISSUE THREAD

**Issue by rosiejane** [PlaceholderAPI/PlaceholderAPI#467]
### Issue
The newest placeholderapi.jar on 1.16.2 now breaks more fish.

PlaceholderAPI-2.10.7-DEV.jar works. But if i update to anything above this then Morefsh does not load. For example 2.10.7 2.10.8 and 2.10.9 break the plugin.

Is there any chance that we can add support for older placeholder hooks? The dev of Morefish has been inactive for around 2 years.

### How to reproduce

1. 

### `/papi dump` output
PlaceholderAPI-2.10.7-DEV.jar does not have /papi dump.

**Comment by Andre601** [comment]
Please provide the console output of the issue.
I have my guess of what is causing this.

**Comment by rosiejane** [comment]
[14:02:10] [Server thread/ERROR]: Error occurred while enabling MoreFish v3.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/external/EZPlaceholderHook
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_202]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-157]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	at me.elsiff.morefish.hooker.PlaceholderApiHooker.hook(PlaceholderApiHooker.kt:18) ~[?:?]
	at me.elsiff.morefish.hooker.PluginHooker$DefaultImpls.hookIfEnabled(PluginHooker.kt:19) ~[?:?]
	at me.elsiff.morefish.hooker.PlaceholderApiHooker.hookIfEnabled(PlaceholderApiHooker.kt:13) ~[?:?]
	at me.elsiff.morefish.MoreFish.onEnable(MoreFish.kt:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-157]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-157]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-157]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-157]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-157]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.external.EZPlaceholderHook
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-157]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-157]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	... 23 more

**Comment by rosiejane** [comment]
> 
> 
> Hello @Andre601,
> 
> The issue you encountered is caused by an Expansion and not PlaceholderAPI itself.
> This issue-tracker is reserved for Bug reports and feature requests towards PlaceholderAPI.
> 
> Please report this issue to the Expansion's main issue-tracker.
> 
> > _This is an automated response created by a GitHub-Action. Responding to or mentioning this bot has no effect!_

Please can you link me on where to do this as im not sure,
Thank you.

**Comment by rosiejane** [comment]
@Andre601

**Comment by Andre601** [comment]
This isn't really our job. You have to ask the dev of that MoreFish plugin to fix this issue as he seems to use a very outdated way of hooking into PlaceholderAPI, which we no longer support.
