### ISSUE TITLE
Makes everything unstable - Using Offline Mode

### ISSUE THREAD

**Issue by 21stCheran** [PlaceholderAPI/PlaceholderAPI#57]
Basically, whenever I use PAPI (latest version, tried from spigot and the dev build) it makes everything go unstable. All the normally working plugins stop working and eventually crash the server. No crash report is generated. And this only happens when I use PAPI. 
Server version : _Paper version git-Paper-446 (MC: 1.13.2)_
PAPI works fine(ish) when run on its own but as soon as I add any other plugin, (PEX specifically) it crashes the server.
Something I see only every time I use PAPI
_java.lang.IllegalStateException: zip file closed
    at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669) ~[?:1.8.0_131]
    at java.util.zip.ZipFile.getEntry(ZipFile.java:309) ~[?:1.8.0_131]
    at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_131]
    at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_131]_

**Comment by darbyjack** [comment]
Can't reproduce. Please re-open if still happening and provide a server startup log file.
