### ISSUE TITLE
Error enabling PlaceholderAPI

### ISSUE THREAD

**Issue by random1167** [PlaceholderAPI/PlaceholderAPI#70]
[New placeholders/plugin]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md
[Request change]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request.md
[Spigot page]: https://www.spigotmc.org/resources/6245/
[Jenkins page]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issue]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

### Notes
This template is for **reporting a bug** and not for requesting changes to the wiki!  
If you want your placeholders added or updated, use the [New placeholders/plugin] or [Request change] template.

Also make sure, that you use the latest version of PlaceholderAPI from either the [Spigot page] or the [Jenkins page] and that your 
issue isn't already listed in the [issue] page.

### Issue
> What is the issue? Describe it like you would tell a friend.

Start up error
```
[06:00:29 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.9.2
[06:00:29 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[06:00:29 ERROR]: Error occurred while enabling PlaceholderAPI v2.9.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/PS
        at com.extendedclip.papi.expansion.plotsquared.PlotSquaredExpansion.register(PlotSquaredExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:120) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:169) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.onEnable(PlaceholderAPIPlugin.java:136) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.PS
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 15 more
```
```
>papi enablecloud
[06:08:42 INFO]: [PlaceholderAPI] Fetching available expansion information...
[06:08:42 INFO]: The cloud has been enabled!
[06:08:43 INFO]: [PlaceholderAPI] 126 placeholder expansions are available on the cloud.
>papi reload
[06:08:49 INFO]: PlaceholderAPI configuration reloaded!
[06:08:49 WARN]: Unexpected exception while parsing console command "papi reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.9.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/PS
        at com.extendedclip.papi.expansion.plotsquared.PlotSquaredExpansion.register(PlotSquaredExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:120) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:169) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:163) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:222) ~[PlaceholderAPI-2.9.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.PS
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        at com.extendedclip.papi.expansion.plotsquared.PlotSquaredExpansion.register(PlotSquaredExpansion.java:48) ~[?:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:120) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:169) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:163) ~[PlaceholderAPI-2.9.2.jar:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:222) ~[PlaceholderAPI-2.9.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-ed274c5]
        ... 8 more
>

```
### Expected behaviour
> What should PlaceholderAPI do?

### Actual behaviour
> What does PlaceholderAPI actually do?

### How to reproduce
> What steps did you made, to get this bug?

1.

**Comment by Andre601** [comment]
This is an issue with the PlotSquared-expansion which has nothing to do with PlaceholderAPI itself.
Just remove the expansion, or use an older version of PlotSquared to fix this issue.

We can't give an ETA on when the expansion will be updated.

**Comment by Andre601** [comment]
[IntellectualSites/PlotSquared-Expansion]: https://github.com/IntellectualSites/PlotSquared-Expansion
[release page]: https://github.com/IntellectualSites/PlotSquared-Expansion/releases

There is now a new expansion that you can use.
You can get it from the [IntellectualSites/PlotSquared-Expansion] repository (from their [release page]).
According to the readme is this page also backwards compatible with the old API.
