### ISSUE TITLE
Not running with Spigot 1.8 anymore

### ISSUE THREAD

**Issue by marcelschoen** [PlaceholderAPI/PlaceholderAPI#784]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

When I put the current PAPI release in a 1.8 Spigot server, the plugin won't load due to a NoClassDefFoundError:
`
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/google/gson/Gson
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-c3c767f-33d5de3]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/Gson
	at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.<clinit>(CloudExpansionManager.java:64) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPIPlugin.<init>(PlaceholderAPIPlugin.java:76) ~[?:?]

`

Since the PAPI resource page says it is compatible with 1.8, I consider this a bug. If it is not, please advise on what to do.

### Expected Behaviour

I don't know.... come with a GSON replacement of its own? Possibly have a special release for older Spigot versions?

### How to Reproduce

1. Set up Spigot 1.8-R0.1-SNAPSHOT-latest server
2. Install latest PAPI plugin release
3. Start server
4. Check log to see "NoClassDefFoundError"

### `/papi dump` Output

N/A

**Comment by marcelschoen** [comment]
To be clear, the only reason why I am even reporting this is because I have a plugin that works together with PAPI, and was asked to make my plugin available for 1.8. That is when I ran into this problem.

**Comment by marcelschoen** [comment]
Oh, just found a workaround - it seems to work when I add this plugin in the 1.8 server:

https://www.spigotmc.org/resources/gson-for-1-8-3-or-older.30852/

**Comment by Andre601** [comment]
Gson has been removed from PAPI to fix an issue with BStats, which does remove 1.8 support.

It was a long discussion we had and at the end did we went with dropping 1.8 in favour of fixing the BStats issues.

**Comment by darbyjack** [comment]
Just update to 1.8.8 or find another workaround.
