### ISSUE TITLE
warn in console with vault

### ISSUE THREAD

**Issue by thekepaag** [PlaceholderAPI/PlaceholderAPI#804]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

[22:21:54] [Craft Scheduler Thread - 10 - PlaceholderAPI/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.11.1 generated an exception while executing task 1247
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at me.itswagpvp.economyplus.vault.VEconomy.getBalance(VEconomy.java:82) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.vault.VEconomy.getBalance(VEconomy.java:88) ~[EconomyPlus.jar:?]
	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:223) ~[?:?]
	at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-176]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behaviour

no error in console

### How to Reproduce

all time in console

### `/papi dump` Output

https://paste.helpch.at/fipaviqeja

**Comment by Starmism** [comment]
Hi, this is a problem with EconomyPlus, not PAPI, as per this line
`me.itswagpvp.economyplus.vault.VEconomy.getBalance(VEconomy.java:82)` ~[EconomyPlus.jar:?]`.
