### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.MinecraftServer

### ISSUE THREAD

**Issue by freaki2010** [PlaceholderAPI/PlaceholderAPI#811]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

[19:36:48 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.MinecraftServer
[19:36:48 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[19:36:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[19:36:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:36:48 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[19:36:48 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[19:36:48 WARN]:        at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:64)
[19:36:48 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:36:48 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[19:36:48 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:36:48 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[19:36:48 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[19:36:48 WARN]:        at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:422)
[19:36:48 WARN]:        at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:162)
[19:36:48 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[19:36:48 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[19:36:48 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[19:36:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:36:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:36:48 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[19:36:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:36:48 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[19:36:48 WARN]:        at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:333)
[19:36:48 WARN]:        at PlaceholderAPI-2.11.1.jar//me.clip.placeholderapi.util.Futures.lambda$onMainThread$0(Futures.java:46)
[19:36:48 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:36:48 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:36:48 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
[19:36:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:36:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Expected Behaviour

That the ClassNotFoundException wont appear.

### How to Reproduce

Put the plugin in a papermc 1.18.1 server and start it.
PlaceholderAPI Version: 2.11.1

### `/papi dump` Output

https://paste.helpch.at/ejiluqesaq

### Console Log

https://paste.helpch.at/udiribelis.md

### Additional Info

https://timings.aikar.co/?id=a71787bbee014d25983654fac3c8e3e6

**Comment by darbyjack** [comment]
Update your server expansion.

**Comment by freaki2010** [comment]
which server expansion? :)

**Comment by iGabyTM** [comment]
The PlaceholderAPI server expansion. `/papi ecloud download server`.

**Comment by freaki2010** [comment]
Thanks for your help guys now it works without any exceptions :) 
Have a nice evening.
