### ISSUE TITLE
PlaceholderAPI Failed to Download Expansion information

### ISSUE THREAD

**Issue by DarrenM999** [PlaceholderAPI/PlaceholderAPI#820]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

API Bug

### What happens?

[23:29:26 WARN]: [PlaceholderAPI] Failed to download expansion information
java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:576) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:565) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
        at java.net.Socket.connect(Socket.java:645) ~[?:?]
        at java.net.Socket.connect(Socket.java:595) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:372) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1299) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1051) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
        at java.net.URL.openStream(URL.java:1192) ~[?:?]
        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.common.io.CharSource.read(CharSource.java:232) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.common.io.Resources.toString(Resources.java:111) ~[patched_1.16.5.jar:git-Paper-794]
        at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$fetch$4(CloudExpansionManager.java:180) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Expected Behaviour

I want to use /papi ecloud download <expansion> , Example : /papi ecloud download Player

### How to Reproduce

1.Type in CMD : /papi ecloud download <expansion>
2.In Chat it says "Failed to find an expansion named : <expansion>"
For example I Type /papi ecloud download Player , but it says "Failed to find an expansion named : Player"
And on the server console it says "[PlaceholderAPI] Failed to download expansion information"

### `/papi dump` Output

https://paste.helpch.at/ucawehifas

### Console Log

Dont Have

### Errors

Dont Have

### Additional Info

![image](https://user-images.githubusercontent.com/84304568/160723845-b5f6ef4f-2122-4c74-9371-aa64c635bbce.png)

**Comment by darbyjack** [comment]
Should your host not allow connections to the PlaceholderAPI eCloud, you can manually download expansions from https://placeholderapi.com/ecloud and place them in your `/plugins/PlaceholderAPI/expansions/` folder.

**Comment by DarrenM999** [comment]
Thankyou Sir
