### ISSUE TITLE
Well first seen issue in 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [PlaceholderAPI/PlaceholderAPI#840]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin/Server Incompatability

### What happens?

Errr in console (see logg)

### Expected Behaviour

No Error in Console

### How to Reproduce

See the log
```
[18:53:19] [ForkJoinPool.commonPool-worker-1/ERROR]: [31m[me.clip.placeholderapi.PlaceholderAPIPlugin] [PlaceholderAPI] failed to load class files of expansions[0m
java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:412) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:207) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:122) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:388) ~[?:?]
	... 7 more
```

### `/papi dump` Output

www.no.dump.needed.com

### Additional Info

Well i know its the first Releases of 1.19 and it may not papi iself..(or is it?)
But to inform i menton it here

**Comment by vlssu** [comment]
I also had a similar problem.
My server plugins all support 1.19 now, but the PlaceholderAPI is causing a lot of problems with the output of many of my plugins.
Hope to release a version supporting 1.19 soon.

https://paste.helpch.at/uqozapawuq

（Could it be that I'm using ViaVersion as well?）

**Comment by ham1255** [comment]
I seen this error outside placeholderapi, either zip file (jar) corrupted or something changed in java

**Comment by CloudeLecaw** [comment]
well i think i can close this since i only see this appearing when the server shuts down.
May its an internal thing :3
