### ISSUE TITLE
ClassCastException on ecloud list

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/PlaceholderAPI#95]
**UPDATED: Version strings...**

Spigot 1.13.2 latest
PlaceholderAPI 2.9.2-DEV-60

### Issue
> What is the issue? Describe it like you would tell a friend.

List attempt produces error in DEV build 60 (see "Actual behavior"). The same sequence works correctly with release 2.9.2-DEV-59 (see "Expected behavior").
Command sequence:
```
papi enablecloud
papi ecloud list installed
papi disablecloud
```

### Expected behaviour
> What should PlaceholderAPI do?

```
>papi enablecloud
[17:55:18 INFO]: [PlaceholderAPI] Fetching available expansion information...
[17:55:18 INFO]: The cloud has been enabled!
[17:55:19 INFO]: [PlaceholderAPI] 125 placeholder expansions are available on the cloud.
>papi ecloud list installed
[17:55:31 INFO]: Showing expansions for: all installed -- amount: 10 page: 1/1
[17:55:31 INFO]: Green = Expansions you have
[17:55:31 INFO]: Gold = Expansions which need updated
[17:55:31 INFO]: 2: Essentials -- http://api.extendedclip.com/media/PAPI-Expansion-Essentials_zn0FSu4.jar
[17:55:31 INFO]: 3: WorldGuard -- http://api.extendedclip.com/media/Expansion-WorldGuard-1.2.0.jar
[17:55:31 INFO]: 4: Vault -- http://api.extendedclip.com/media/PAPI-Expansion-Vault_EetNHIo.jar
[17:55:31 INFO]: 5: Player -- http://api.extendedclip.com/media/PAPI-Expansion-Player_khA7VpR.jar
[17:55:31 INFO]: 6: Skript -- http://api.extendedclip.com/media/Expansion-Skript_bGsPupR.jar
[17:55:31 INFO]: 7: LuckPerms -- http://api.extendedclip.com/media/Expansion-LuckPerms_2ZvigdN.jar
[17:55:31 INFO]: 8: Multiverse -- http://api.extendedclip.com/media/Expansion-Multiverse.jar
[17:55:31 INFO]: 9: ViaVersion -- http://api.extendedclip.com/media/Expansion-ViaVersion_yeaWuoM.jar
[17:55:31 INFO]: 10: Thirst -- http://api.extendedclip.com/media/Expansion-Thirst_BWspLom.jar
>papi disablecloud
[17:55:38 INFO]: The cloud has been disabled!
```

### Actual behaviour
> What does PlaceholderAPI actually do?

```
>papi enablecloud
[17:56:31 INFO]: [PlaceholderAPI] Fetching available expansion information...
[17:56:31 INFO]: The cloud has been enabled!
[17:56:32 INFO]: [PlaceholderAPI] 125 placeholder expansions are available on the cloud.
>papi ecloud list installed
[17:56:40 INFO]: Showing expansions for: all installed -- amount: 9 page: 1/1
[17:56:40 INFO]: Green = Expansions you have
[17:56:40 INFO]: Gold = Expansions which need updated
[17:56:40 WARN]: Unexpected exception while parsing console command "papi ecloud list installed"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.9.2-DEV-60
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class java.util.TreeMap$Entry cannot be cast to class java.lang.Comparable (java.util.TreeMap$Entry and java.lang.Comparable are in module java.base of loader 'bootstrap')
        at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?]
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at me.clip.placeholderapi.commands.ExpansionCloudCommands.onCommand(ExpansionCloudCommands.java:323) ~[?:?]
        at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:101) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        ... 8 more
>papi disablecloud
[17:56:47 INFO]: The cloud has been disabled!
```

### How to reproduce
> What steps did you made, to get this bug?

1. Install PlaceholderAPI 2.9.2-DEV-60
1. Start server
1. Run command sequence above

**Comment by extendedclip** [comment]
Shit alright I guess I have to fire up the pc and sort this out. My fault for blindly merging without reviewing everything....

**Comment by SlimeDog** [comment]
BTW
> papi list

works great; list is alphabetized.

**Comment by SlimeDog** [comment]
Any progress on this issue?

**Comment by Andre601** [comment]
> PlaceholderAPI 2.5.2-DEV-60

Is this a typo? Latest release is 2.9.2, so why is the dev version lower?

**Comment by SlimeDog** [comment]
> > PlaceholderAPI 2.5.2-DEV-60
> 
> Is this a typo? Latest release is 2.9.2, so why is the dev version lower?

Yes, clearly. See UPDATED comments. The issue is with 2.9.2-60. It works fine with 2.9.2-59 (but doesn't sort, of course).

**Comment by SlimeDog** [comment]
Confirmed PAPI 2.10.0 working nicely on both Spigot 1.13.2 final and Spigot 1.14 (2254). Thank you.

**Comment by darbyjack** [comment]
Yw!
