### ISSUE TITLE
in 1.20 %player_ping% does not work. error:

### ISSUE THREAD

**Issue by welove69** [PlaceholderAPI/PlaceholderAPI#971]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

in 1.20.1 %player_ping% does not work. error:
Request adaptation 1.20.1

### Expected Behaviour

Request adaptation 1.20.1

### How to Reproduce

in 1.20.1 %player_ping% does not work. error:

### `/papi dump` Output

in 1.20.1 %player_ping% does not work. error:

### Console Log

[12:02:16 WARN]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int [12:02:16 WARN]: at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIllegalArgumentException(FieldAccessorImpl.java:130) [12:02:16 WARN]: at java.base/jdk.internal.reflect.FieldAccessorImpl.newGetIntIllegalArgumentException(FieldAccessorImpl.java:193) [12:02:16 WARN]: at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.getInt(MethodHandleObjectFieldAccessorImpl.java:84) [12:02:16 WARN]: at java.base/java.lang.reflect.Field.getInt(Field.java:628) [12:02:16 WARN]: at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66) [12:02:16 WARN]: at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50) [12:02:16 WARN]: at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122) [12:02:16 WARN]: at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481) [12:02:16 WARN]: at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403) [12:02:16 WARN]: at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) [12:02:16 WARN]: at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) [12:02:16 WARN]: at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholderAPI(PlaceholderHandler.java:67) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replaceBoth(PlaceholderHandler.java:61) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholdersThrows(PlaceholderHandler.java:37) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboardLine.update(PlayerScoreboardLine.java:125) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.update(PlayerScoreboard.java:91) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.objects.ScoreboardPlayer.tickScoreboards(ScoreboardPlayer.java:448) [12:02:16 WARN]: at AnimatedScoreboard-0.2.9.jar//me.jasperjh.animatedscoreboard.core.PlayerScoreboardHandler.lambda$init$2(PlayerScoreboardHandler.java:204) [12:02:16 WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) [12:02:16 WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [12:02:16 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [12:02:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [12:02:16 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [12:02:16 WARN]: at java.base/java.lang.Thread.run(Thread.java:1623)

### Errors

in 1.20.1 %player_ping% does not work. error:

### Additional Info

Request adaptation 1.20.1

**Comment by Starmism** [comment]
You didn't attach an actual `/papi dump` output, but I'm guessing you're on an older version. A Player expansion release for 1.20 (2.0.5) was released yesterday, you can download it from [this url](https://api.extendedclip.com/expansions/player/) or in-game with the ecloud.
