### ISSUE TITLE
java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/PlaceholderExpansion

### ISSUE THREAD

**Issue by imyoric** [PlaceholderAPI/PlaceholderAPI#998]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [ ] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

API Bug

### What happens?

My plugin is not loading even though the PlaceHolderAPI is present and has already loaded.

```
[14:33:03 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[14:33:03 INFO]: [PlaceholderAPI] Fetching available expansion information...
[14:33:03 INFO]: [ServerBackup] Enabling ServerBackup v2.9.7
[14:33:03 INFO]: [ServerBackup] ServerBackup: Plugin enabled.
[14:33:03 INFO]: [ServerBackup] ServerBackup: Searching for updates...
[14:33:03 INFO]: [SecretPlugin202] Enabling SecretPlugin202 v1.0
[14:33:03 INFO]: [SecretPlugin202] PlaceholderAPI Founded!
[14:33:03 ERROR]: Error occurred while enabling SecretPlugin202 v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/PlaceholderExpansion
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:114) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at ru.yoricya.minecraft.plugins.vanilla.sp202.Main.onEnable(Main.java:15) ~[SecretPlugin202-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.reload(CraftServer.java:1117) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.Bukkit.reload(Bukkit.java:951) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:970) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-117]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.expansion.PlaceholderExpansion
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.1.jar:git-Paper-117]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-117]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
```

### Expected Behaviour

Plugin loads and works without errors

### How to Reproduce

Loading PlaceholderExpansion:
```
 @Override
    public void onEnable() {
        if(Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != null) {
            this.getLogger().info("PlaceholderAPI Founded!");
            (new WorldColorHolder(this)).register();
        }else{
            this.getLogger().info("PlaceholderAPI отсутствует!");
        }
    }
```

PlaceholderExpansion:
```
package ru.yoricya.minecraft.plugins.vanilla.sp202;
import me.clip.placeholderapi.expansion.PlaceholderExpansion;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

import static ru.yoricya.minecraft.plugins.vanilla.sp202.Main.getPlayerWorldPrefix;

public class WorldColorHolder extends PlaceholderExpansion {

    private Main plugin;

    public WorldColorHolder(Main plugin) {
        this.plugin = plugin;
    }

    @Override
    public String getAuthor() {
        return "Yoricya";
    }

    @Override
    public String getIdentifier() {
        return "worldcolor";
    }

    @Override
    public String getVersion() {
        return "1.0";
    }

    @Override
    public boolean persist() {
        return true; // This is required or else PlaceholderAPI will unregister the Expansion on reload
    }
    @Override
    public boolean canRegister() {
        return (plugin = (Main) Bukkit.getPluginManager().getPlugin(getRequiredPlugin())) != null;
    }

    @Override
    public String onPlaceholderRequest(Player player, String params) {
        if(params.equalsIgnoreCase("color")){
            return getPlayerWorldPrefix(player);
        }

        if(params.equalsIgnoreCase("colored_nick")) {
            return getPlayerWorldPrefix(player)+player.getName();
        }

        return null; // Placeholder is unknown by the Expansion
    }
}

```

### `/papi dump` Output

https://paste.helpch.at/woyuhosaca

### Console Log

https://paste.helpch.at/ikumuzeyun.makefile

### Errors

https://paste.helpch.at/kavodigihi.css

**Comment by imyoric** [comment]
I managed to fix it! I switched from PaperAPI to SpigotAPI and it worked!
